name: Build package and deploy to PyPI

on:
  release:
    types: [ published ]

jobs:
  build_deploy:
    name: Build and deploy
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true

    - uses: actions/setup-python@v2
      name: Install Python
      with:
        python-version: 3.9

    - name: Install requirements

      run: |
        python -m pip install -U pip
        python -m pip install twine wheel

    - name: Build wheels and sdist
      run: |
         python setup.py sdist bdist_wheel

    - uses: actions/upload-artifact@v2
      with:
        name: wheels
        path: ./dist

    - name: Publish package to PyPi
      uses: pypa/gh-action-pypi-publish@master
      with:
        user: __token__
        password: ${{ secrets.PYPI_PASSWORD }}

  conda:
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.7, 3.8, 3.9]
    name: Build and package for Conda
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
    - name: Set up Anaconda build
      uses: s-weigand/setup-conda@v1
      with:
        conda-channels: wvxvw
        python-version: ${{ matrix.python-version }}
    - run: python setup.py bdist_egg
    - run: python ./scripts/gen-conda-recipe.py
    - run: conda install conda-build anaconda-client conda-verify
    - run: conda build -c conda-forge --output-folder ./dist ./conda-pkg/
    - run: conda convert -p osx-64 -o ./dist ./dist/linux-64/*.tar.bz2
    - run: conda convert -p win-64 -o ./dist ./dist/linux-64/*.tar.bz2
    - run: >
        ANACONDA_API_TOKEN=${{ secrets.ANACONDA_TOKEN }}
        anaconda upload --label main ./dist/linux-64/*py37_0.tar.bz2
    - run: >
        ANACONDA_API_TOKEN=${{ secrets.ANACONDA_TOKEN }}
        anaconda upload --label main ./dist/osx-64/*py37_0.tar.bz2
    - run: >
        ANACONDA_API_TOKEN=${{ secrets.ANACONDA_TOKEN }}
        anaconda upload --label main ./dist/win-64/*py37_0.tar.bz2
